@component('mail::message')

    {{ __('Respected') }} {{ $data['item']->user?->fullName() }},

    {!! __('notifications_msg.legislative_initiative.success.main_text') !!}

    {{ __('custom.name') }}: {{ __('custom.change_f') }} {{ __('custom.in') }} {{ $data['item']->law?->name }}\
    {{ __('site.email.li.change') }}: {{ strip_tags(html_entity_decode($data['item']->description)) ?? '' }}\
    {{ __('custom.author') }} : {{ $data['item']->user?->fullName() }}\
    {{ __('site.email.li.law_institution') }} : {{ $data['item']->law && $data['item']->law->institutions->count() ? join(';', $data['item']->law->institutions->pluck('name')->toArray()) : '' }}\
    {{ __('Link to the legislative initiative on the Public Consultation Portal') }}:
    @if(isset($data['url']) && !empty($data['url']))
        @component('mail::link', ['url' => $data['url']])
            {{ __('See the legislative initiative') }}
        @endcomponent
    @endif

    {{ __('Change subscriptions here') }}
    @component('mail::link', ['url' => route('profile', ['tab' => 'subscriptions'])])
        {{ __("Subscription's management") }}
    @endcomponent

    {{ __('Autogenerated email') }}

@endcomponent
