@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{{ $text }}

{{ __('custom.name') }}: {{ $modelInstance->name }}<br>
{{ trans_choice('custom.field_of_actions', 1) }}: {{ $modelInstance->policyArea?->name }}<br>
{{ __('validation.attributes.authority_id') }}: {{ $modelInstance->authority?->name }}<br>
{{ __('custom.chairman') }}: {{ $modelInstance->advisoryChairmanType?->name }}<br>
{{ __('Link to the adv board on the Public Consultation Portal') }}:
@component('mail::button', ['url' => $url])
    {{ __('See the adv board') }}
@endcomponent

{{ __('Change subscriptions here') }}
@component('mail::button', ['url' => route('profile', ['tab' => 'subscriptions'])])
    {{ __("Subscription's management") }}
@endcomponent

{{ __('Autogenerated email') }}

@endcomponent
