@component('mail::message')

    {{ __('Respected') }} {{ $user->fullName() }},

    {!! $text !!}

    {{ __('custom.name') }}: {{ __('custom.change_f') }} {{ __('custom.in') }} {{ $modelInstance->law?->name }}\
    {{ __('site.email.li.change') }}: {{ strip_tags(html_entity_decode($modelInstance->description)) ?? '' }}\
    {{ __('custom.author') }} : {{ $modelInstance->user?->fullName() }}\
    {{ __('site.email.li.law_institution') }} : {{ $modelInstance->law && $modelInstance->law->institutions->count() ? join(';', $modelInstance->law->institutions->pluck('name')->toArray()) : '' }}\
    {{ __('Link to the legislative initiative on the Public Consultation Portal') }}:
    @component('mail::link', ['url' => $url])
        {{ __('See the legislative initiative') }}
    @endcomponent

    {{ __('Change subscriptions here') }}
    @component('mail::link', ['url' => route('profile', ['tab' => 'subscriptions'])])
        {{ __("Subscription's management") }}
    @endcomponent

    {{ __('Autogenerated email') }}

@endcomponent
