@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{!! $text !!}

{{ __('custom.name') }}: {{ __('custom.change_f') }} {{ __('custom.in') }} {{ $modelInstance->law?->name }}<br>
{{ __('site.email.li.change') }}: {{ strip_tags(html_entity_decode($modelInstance->description)) ?? '' }}<br>
{{ __('custom.author') }} : {{ $modelInstance->user?->fullName() }}<br>
{{ __('site.email.li.law_institution') }} : {{ $modelInstance->law && $modelInstance->law->institutions->count() ? join(';', $modelInstance->law->institutions->pluck('name')->toArray()) : '' }}<br>
{{ __('Link to the legislative initiative on the Public Consultation Portal') }}:
@component('mail::button', ['url' => $url])
    {{ __('See the legislative initiative') }}
@endcomponent

@if(isset($data['showSubscriptionLink']) && $data['showSubscriptionLink'])
{{ __('Change subscriptions here') }}
@component('mail::button', ['url' => route('profile', ['tab' => 'subscriptions'])])
    {{ __("Subscription's management") }}
@endcomponent
@endif

{{ __('Autogenerated email') }}

@endcomponent
