@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{{ $text }}

{{ __('Link to the program on the Public Consultation Portal') }}:
@component('mail::button', ['url' => $url])
    {{ __('See the consultation') }}
@endcomponent

{{ __('Change subscriptions here') }}
@component('mail::button', ['url' => route('profile', ['tab' => 'subscriptions'])])
    {{ __("Subscription's management") }}
@endcomponent

{{ __('Autogenerated email') }}

@endcomponent
