@component('mail::message')

Уважаеми {{ $user->fullName() }},

{{ $text }}

Уникален номер на консултацията: {{ $modelInstance->reg_num }}
Наименование: {{ $modelInstance->getModelName() }}
Период на консултацията: {{ displayDate($modelInstance->open_from) }} - {{ displayDate($modelInstance->open_to) }} г.
Линк към консултацията на Портала за обществени консултации: <а href="{{ $url }}" target="_blank">Вижте консултацията</а>
@component('mail::button', ['url' => $url])
    Вижте консултацията
@endcomponent

{{ __('Autogenerated email') }}

@endcomponent
