@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{{ $text }}

{{ __('custom.consultation_number') }}: {{ $modelInstance->reg_num }}\
{{ __('custom.name') }}: {{ $modelInstance->getModelName() }}\
{{ trans_choice('custom.field_of_actions', 1) }}: {{ $modelInstance->fieldOfAction?->translation?->name }}\
{{ trans_choice('custom.institutions', 1) }}: {{ $modelInstance->responsibleInstitution?->translation?->name }}\
{{ __('Consultation period') }} : {{ displayDate($modelInstance->open_from) }} - {{ displayDate($modelInstance->open_to) }} г.\
{{ __('Link to the consultation on the Public Consultation Portal') }}:
@component('mail::link', ['url' => $url])
{{ __('See the consultation') }}
@endcomponent

{{ __('Autogenerated email') }}

@endcomponent
