@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{{ $text }}

{{ __('custom.name') }}: {{ $modelInstance->title }}<br>
{{ trans_choice('custom.categories', 1) }}: {{ $modelInstance->category?->name }}<br>
{{ __('Link to the publication on the Public Consultation Portal') }}:
@component('mail::button', ['url' => $url])
    {{ __('See the publication') }}
@endcomponent

@if(isset($data['showSubscriptionLink']) && $data['showSubscriptionLink'])
{{ __('Change subscriptions here') }}
@component('mail::button', ['url' => route('profile', ['tab' => 'subscriptions'])])
    {{ __("Subscription's management") }}
@endcomponent
@endif

{{ __('Autogenerated email') }}

@endcomponent
