@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{{ $text }}

{{ __('custom.consultation_number') }}: {{ $modelInstance->reg_num }}<br>
{{ __('custom.name') }}: {{ $modelInstance->getModelName() }}<br>
{{ trans_choice('custom.field_of_actions', 1) }}: {{ $modelInstance->fieldOfAction?->translation?->name }}<br>
{{ trans_choice('custom.institutions', 1) }}: {{ $modelInstance->responsibleInstitution?->translation?->name }}<br>
{{ __('Consultation period') }} : {{ displayDate($modelInstance->open_from) }} - {{ displayDate($modelInstance->open_to) }} г.<br>
{{ __('Link to the consultation on the Public Consultation Portal') }}:
@component('mail::button', ['url' => $url])
    {{ __('See the consultation') }}
@endcomponent

{{ __('Change subscriptions here') }}
@component('mail::button', ['url' => route('profile', ['tab' => 'subscriptions'])])
    {{ __("Subscription's management") }}
@endcomponent

{{ __('Autogenerated email') }}

@endcomponent
