@component('mail::message')

{{ __('Respected') }} {{ $user->fullName() }},

{{ $text }}

{{ __('custom.name') }}: {{ $modelInstance->name }}<br>
{{ __('custom.consultation_number') }}: {{ $secondModelInstance->reg_num }}<br>
{{ __('custom.name') }}: {{ $secondModelInstance->getModelName() }}<br>
{{ trans_choice('custom.field_of_actions', 1) }}: {{ $secondModelInstance->fieldOfAction?->translation?->name }}<br>
{{ trans_choice('custom.institutions', 1) }}: {{ $secondModelInstance->responsibleInstitution?->translation?->name }}<br>
{{ __('Consultation period') }} : {{ displayDate($secondModelInstance->open_from) }} - {{ displayDate($secondModelInstance->open_to) }} г.<br>
{{ __('Link to the consultation on the Public Consultation Portal') }}:
@component('mail::button', ['url' => $url])
    {{ __('See the consultation') }}
@endcomponent

@if(isset($data['showSubscriptionLink']) && $data['showSubscriptionLink'])
{{ __('Change subscriptions here') }}
@component('mail::button', ['url' => route('profile', ['tab' => 'subscriptions'])])
    {{ __("Subscription's management") }}
@endcomponent
@endif

{{ __('Autogenerated email') }}

@endcomponent
