<?php
return [
    [
        'name_bg'       => 'Дактилоскопия',
        'name_en'       => 'PRINTS', // Fingerprints
        'abbr_bg'       => 'ДКТ',
        'abbr_en'       => 'P',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Трасология и балистика',
        'name_en'       => 'BALLISTICS',
        'abbr_bg'       => 'БАЛ',
        'abbr_en'       => 'F',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Документни изследвания',
        'name_en'       => 'QDH',
        'abbr_bg'       => 'ДОК',
        'abbr_en'       => 'H',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Документни изследвания, фоноскопия и видео анализ',
        'name_en'       => 'QD',
        'abbr_bg'       => 'ДИФФ',
        'abbr_en'       => 'Q',
        'visible'       => false,
        'active'        => false,
    ],
    [
        'name_bg'       => 'ДНК анализ',
        'name_en'       => 'DNA',
        'abbr_bg'       => 'ДНК',
        'abbr_en'       => 'D',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Физикохимия',
        'name_en'       => 'CHEMISTRY',
        'abbr_bg'       => 'ФЗХ',
        'abbr_en'       => 'C',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Наркотици',
        'name_en'       => 'DRUGS',
        'abbr_bg'       => 'НАР',
        'abbr_en'       => 'N',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Токсикохимия',
        'name_en'       => 'TC',
        'abbr_bg'       => 'ТКХ',
        'abbr_en'       => 'B',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Биология',
        'name_en'       => 'BIOLOGY',
        'abbr_bg'       => 'БТМ',
        'abbr_en'       => 'B',
        'visible'       => false,
        'active'        => false,
    ],
    [
        'name_bg'       => 'Одорология',
        'name_en'       => 'ODOROLOGY',
        'abbr_bg'       => 'ОДО',
        'abbr_en'       => 'B',
        'visible'       => false,
        'active'        => false,
    ],
    [
        'name_bg'       => 'Идентификационни изследвания',
        'name_en'       => 'ID',
        'abbr_bg'       => 'ИДИ',
        'abbr_en'       => 'I',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Електронни устройства',
        'name_en'       => 'ED',
        'abbr_bg'       => 'ИЕУ',
        'abbr_en'       => 'E',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Комптърни системи',
        'name_en'       => 'IT',
        'abbr_bg'       => 'КСМ',
        'abbr_en'       => 'K',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Комуникационни устройства',
        'name_en'       => 'CD',
        'abbr_bg'       => 'ИКУ',
        'abbr_en'       => 'T',
        'visible'       => true,
        'active'        => true,
    ],
    [
        'name_bg'       => 'Деловодство',
        'name_en'       => 'RM',
        'abbr_bg'       => 'ДЕЛОВ',
        'abbr_en'       => 'R',
        'visible'       => true,
        'active'        => false,
    ],
];
