<?php
return [
    'form1' => [
        'step1' => [
            'institution' => 'required',
            'regulatory_act' => 'required',
            'included_in_program' => 'required',
            'contact_person' => 'required',
            'phone' => 'required',
            'email' => 'required|email',
            'problem_to_solve.*' => 'required',
            'goals.*' => 'required',
            'interested_parties.*.text' => 'required',
            'interested_parties.*.number' => 'required',
        ],
        'step2' => [
            'variants.*.*.description' => 'required',
            'variants.*.*.positive_impact' => 'required',
            'variants.*.*.negative_impact' => 'required',
            'variants.*.*.small_mid_impact' => 'required',
            'variants.*.*.admin_weight' => 'required',
            'comparison.*.*.*.*' => 'required',
        ],
        'step3' => [
            'chosen_variants.*' => 'required',
            'change_admin_weight' => 'required',
            'change_admin_weight_text' => 'required_if:change_admin_weight,0,1',
            'affects_regulatory_acts' => 'required',
            'affects_regulatory_acts_text' => 'required_if:affects_regulatory_acts,1',
            'affects_registry' => 'required',
            'affects_registry_text' => 'required_if:affects_registry,1',
            'affects_companies' => 'required',
            'potential_risks' => 'required',
        ],
        'step4' => [
            'conducted_consultations' => 'required',
            'conducted_consultations_text' => 'required_if:conducted_consultations,1',
            'not_conducted_consultations_text' => 'required_if:conducted_consultations,0',
            'is_from_eu' => 'required',
            'is_from_eu_text' => 'required_if:is_from_eu,1',
            'initial_assessment_required' => 'required',
            'applications' => 'required',
            'info_sources' => 'required',
            'name' => 'required',
            'job' => 'required',
            'date' => 'required',
        ],
    ],

    'form2' => [
        'step1' => [
            'institution' => 'required',
            'regulatory_act' => 'required',
            'period_assessment' => 'required',
            'level' => 'required',
            'contact_person' => 'required',
            'phone' => 'required',
            'email' => 'required|email',
            'problem_to_solve.*' => 'required',
        ],
        'step2' => [
            'goals.*' => 'required',
            'variant_simple.*.*' => 'required',
        ],
        'step3' => [
            'variants.*.*.description' => 'required',
            'variants.*.*.positive_impact' => 'required',
            'variants.*.*.negative_impact' => 'required',
            'variants.*.*.small_mid_impact' => 'required',
            'variants.*.*.admin_weight' => 'required',
            'variants.*.*.risks' => 'required',
        ],
        'step4' => [
            'expenses.*.*.expenses' => 'required',
            'expenses.*.*.benefits' => 'required',
            'consultations' => 'required',
            'effective_from' => 'required',
            'responsibility' => 'required',
            'name' => 'required',
            'job' => 'required',
            'date' => 'required',
        ],
    ],

    'form3' => [
        'step1' => [
            'problem_to_solve.*' => 'required',
            'interested_parties.*.text' => 'required',
            'interested_parties.*.number' => 'required',
        ],
        'step2' => [
            'goals.*.*' => 'required',
            'variant_simple.*.*' => 'required',
        ],
        'step3' => [
            'variants.*.*.economic_impacts' => 'required',
            'variants.*.*.social_impact' => 'required',
            'variants.*.*.ecologic_impact' => 'required',
            'variants.*.*.specific_impact_1' => 'required',
            'variants.*.*.specific_impact_2' => 'required',
            'quality_assessment' => 'required',
        ],
        'step4' => [],
        'step5' => [],
        'step6' => [],
        'step7' => [],
        'step8' => [],
    ],
    'form4' => [
        'step1' => [
        ],
        'step2' => [
            'resume' => 'required',
            'introduction' => 'required',
            'goals.*' => 'required',
        ],
        'step3' => [
            'changes.*.investigate_changes' => 'required',
            'changes.*.problem_to_solve.*' => 'required',
            'changes.*.resources_used' => 'required',
            'changes.*.achieved_results' => 'required',
            'changes.*.direct_effects' => 'required',
            'changes.*.impacts' => 'required',
            'changes.*.links_regulatory_acts' => 'required',
            'changes.*.main_highlights' => 'required',
            'changes.*.results_court' => 'required',
            'changes.*.criteria1' => 'required',
            'changes.*.criteria2' => 'required',
            'changes.*.criteria3' => 'required',
            'changes.*.criteria4' => 'required',
            'changes.*.criteria5' => 'required',
            'changes.*.questions.*' => 'required',
        ],
        'step4' => [
            'collected_data.*.interested_parties' => 'required',
            'collected_data.*.consultations' => 'required',
            'collected_data.*.sources' => 'required',
        ],
        'step5' => [
            'analysis.*.answers_info' => 'required',
            'analysis.*.results' => 'required',
        ],
        'step6' => [
            'impact.*.conclusion' => 'required',
            'conclusions' => 'required',
            'distribution' => 'required',
            'recommendations' => 'required',
            'sources' => 'required',
        ],
    ],
];