<?php
return [
    'form1' => [
        'step1' => [
            'institution' => 'required',
            'regulatory_act' => 'required',
            'included_in_program' => 'required',
            'contact_person' => 'required',
            'phone' => 'required',
            'email' => 'required|email',
            'problem_to_solve.*' => 'required',
            'goals.*' => 'required',
            'interested_parties.*.text' => 'required',
            'interested_parties.*.number' => 'required',
        ],
        'step2' => [
            'variants.*.*.description' => 'required',
            'variants.*.*.positive_impact' => 'required',
            'variants.*.*.negative_impact' => 'required',
            'variants.*.*.small_mid_impact' => 'required',
            'variants.*.*.admin_weight' => 'required',
            'comparison.*.*.*.*' => 'required',
        ],
        'step3' => [
            'chosen_variants.*' => 'required',
            'change_admin_weight' => 'required',
            'change_admin_weight_text' => 'required_if:change_admin_weight,0,1',
            'affects_regulatory_acts' => 'required',
            'affects_regulatory_acts_text' => 'required_if:affects_regulatory_acts,1',
            'affects_registry' => 'required',
            'affects_registry_text' => 'required_if:affects_registry,1',
            'affects_companies' => 'required',
            'potential_risks' => 'required',
        ],
        'step4' => [
            'conducted_consultations' => 'required',
            'conducted_consultations_text' => 'required_if:conducted_consultations,1',
            'not_conducted_consultations_text' => 'required_if:conducted_consultations,0',
            'is_from_eu' => 'required',
            'is_from_eu_text' => 'required_if:is_from_eu,1',
            'initial_assessment_required' => 'required',
            'applications' => 'required',
            'info_sources' => 'required',
            'name' => 'required',
            'job' => 'required',
            'date' => 'required',
        ],
    ],

    'form2' => [
        'step1' => [
            'institution' => 'required',
            'regulatory_act' => 'required',
            'period_assessment' => 'required',
            'level' => 'required',
            'contact_person' => 'required',
            'phone' => 'required',
            'email' => 'required|email',
            'problem_to_solve.*' => 'required',
        ],
        'step2' => [
            'goals.*' => 'required',
            'variant_simple.*.*' => 'required',
        ],
        'step3' => [
            'variants.*.*.description' => 'required',
            'variants.*.*.positive_impact' => 'required',
            'variants.*.*.negative_impact' => 'required',
            'variants.*.*.small_mid_impact' => 'required',
            'variants.*.*.admin_weight' => 'required',
            'variants.*.*.risks' => 'required',
        ],
        'step4' => [
            'expenses.*.*.expenses' => 'required',
            'expenses.*.*.benefits' => 'required',
            'consultations' => 'required',
            'effective_from' => 'required',
            'responsibility' => 'required',
            'name' => 'required',
            'job' => 'required',
            'date' => 'required',
        ],
    ],

    'form3' => [
        'step1' => [
            'problem_to_solve.*' => 'required',
        ],
    ],
];