@component('mail::message')

Здравейте,

Получено е съобщение, чрез контактната форма на Порталът за обществени консултации.

Съобщение:
@component('mail::panel')
    {{ $message }}
@endcomponent

{{ __('Autogenerated email') }}
@endcomponent
