<?php

namespace App\Models;

use App\Enums\AdvisoryTypeEnum;
use App\Enums\DocTypesEnum;
use App\Traits\FilterSort;
use Astrotomic\Translatable\Translatable;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Collection;

/**
 * @property int                      $id
 * @property string                   $name
 *
 * @property Collection               $members
 * @property AdvisoryBoardFunction    $advisoryFunction
 * @property Collection               $functionFiles
 * @property Collection               $secretaryCouncil
 * @property AdvisoryBoardSecretariat $secretariat
 * @property Collection               $meetings
 * @property Collection               $regulatoryAllFiles
 * @property Collection               $regulatoryFiles
 * @property Collection               $moderators
 *
 * @method static orderBy(string $string, string $string1)
 * @method static find(mixed $get)
 */
class AdvisoryBoard extends ModelActivityExtend
{

    use FilterSort, Translatable;

    const PAGINATE = 20;
    const MODULE_NAME = ('custom.advisory_board');
    const TRANSLATABLE_FIELDS = ['name', 'advisory_specific_name', 'advisory_act_specific_name', 'report_institution_specific_name'];

    public array $translatedAttributes = self::TRANSLATABLE_FIELDS;
    public $timestamps = true;

    protected $table = 'advisory_boards';

    //activity
    protected string $logName = "advisory_board";

    protected $fillable = ['policy_area_id', 'advisory_chairman_type_id', 'advisory_act_type_id', 'meetings_per_year', 'has_npo_presence', 'authority_id', 'integration_link'];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // global scope to show only self moderated advisory boards
        if (
            !is_null(auth()->user()) &&
            !auth()->user()->hasRole(CustomRole::MODERATOR_ADVISORY_BOARDS) &&
            auth()->user()->hasRole(CustomRole::MODERATOR_ADVISORY_BOARD
            )
        ) {
            static::addGlobalScope('moderator', function (Builder $builder) {
                $builder->whereIn('id', AdvisoryBoardModerator::where('user_id', auth()->user()->id)->pluck('advisory_board_id'));
            });
        }
    }

    public function moderators(): HasMany
    {
        return $this->hasMany(AdvisoryBoardModerator::class);
    }

    public function customSections(): HasMany
    {
        return $this->hasMany(AdvisoryBoardCustom::class)->orderBy('order');
    }

    public function moderatorFiles(): HasMany
    {
        return $this->hasMany(File::class, 'id_object')
            ->where(['code_object' => File::CODE_AB_FUNCTION, 'doc_type' => DocTypesEnum::AB_MODERATOR]);
    }

    public function moderatorInformation(): HasOne
    {
        return $this->hasOne(AdvisoryBoardModeratorInformation::class);
    }

    public function regulatoryFiles(): HasMany
    {
        return $this->hasMany(File::class, 'id_object')
            ->where(['code_object' => File::CODE_AB_FUNCTION, 'doc_type' => DocTypesEnum::AB_REGULATORY_FRAMEWORK]);
    }

    public function regulatoryAllFiles(): HasMany
    {
        return $this->hasMany(File::class, 'id_object')
            ->withTrashed()
            ->where(['code_object' => File::CODE_AB_FUNCTION, 'doc_type' => DocTypesEnum::AB_REGULATORY_FRAMEWORK]);
    }

    public function members(): HasMany
    {
        return $this->hasMany(AdvisoryBoardMember::class)
            ->where('advisory_type_id', AdvisoryTypeEnum::MEMBER->value);
    }

    public function viceChairmen(): HasMany
    {
        return $this->hasMany(AdvisoryBoardMember::class)
            ->where('advisory_type_id', AdvisoryTypeEnum::CHAIRMAN->value)
            ->where('advisory_chairman_type_id', AdvisoryChairmanType::VICE_CHAIRMAN);
    }

    public function chairmen(): HasMany
    {
        return $this->hasMany(AdvisoryBoardMember::class)
            ->where('advisory_type_id', AdvisoryTypeEnum::CHAIRMAN->value)
            ->where('advisory_chairman_type_id', AdvisoryChairmanType::HEAD_CHAIRMAN);
    }

    public function advisoryFunction(): HasOne
    {
        return $this->hasOne(AdvisoryBoardFunction::class);
    }

    protected function hasViceChairman(): Attribute
    {
        return Attribute::make(
            get: function () {
                if ($this->members->count() > 0) {
                    $found = $this->members->first(fn($member) => $member->advisory_chairman_type_id === AdvisoryChairmanType::VICE_CHAIRMAN);

                    return !is_null($found);
                }

                return false;
            }
        );
    }

    public function meetings(): HasMany
    {
        return $this->hasMany(AdvisoryBoardMeeting::class)
            ->whereYear('created_at', Carbon::now()->year);
    }

    public function secretariat(): HasOne
    {
        return $this->hasOne(AdvisoryBoardSecretariat::class);
    }

    public function secretaryCouncil(): HasMany
    {
        return $this->hasMany(AdvisoryBoardSecretaryCouncil::class);
    }

    public function authority(): BelongsTo
    {
        return $this->belongsTo(AuthorityAdvisoryBoard::class);
    }

    public function allMembers(): HasMany
    {
        return $this->hasMany(AdvisoryBoardMember::class);
    }

    public function advisoryActType(): BelongsTo
    {
        return $this->belongsTo(AdvisoryActType::class);
    }

    public function advisoryChairmanType(): BelongsTo
    {
        return $this->belongsTo(AdvisoryChairmanType::class);
    }

    public function policyArea(): BelongsTo
    {
        return $this->belongsTo(PolicyArea::class);
    }

    /**
     * Get the model name
     */
    public function getModelName(): string
    {
        return $this->name;
    }

    public static function translationFieldsProperties(): array
    {
        return [
            'name' => [
                'type' => 'string',
                'rules' => ['required'],
            ],
        ];
    }
}
